import React from 'react';
import { View, Text, FlatList, StyleSheet } from 'react-native';

const animeData = [
  { id: '1', title: 'Attack on Titan' },
  { id: '2', title: 'Naruto' },
  { id: '3', title: 'One Piece' },
  { id: '4', title: 'Demon Slayer' },
  { id: '5', title: 'Death Note' },
  { id: '6', title: 'Fullmetal Alchemist: Brotherhood' },
  { id: '7', title: 'My Hero Academia' },
  { id: '8', title: 'Jujutsu Kaisen' },
  { id: '9', title: 'Tokyo Ghoul' },
  { id: '10', title: 'Bleach' },
  { id: '11', title: 'Hunter x Hunter' },
  { id: '12', title: 'Dragon Ball Z' },
  { id: '13', title: 'Sword Art Online' },
  { id: '14', title: 'Black Clover' },
  { id: '15', title: 'Fairy Tail' },
  { id: '16', title: 'One Punch Man' },
  { id: '17', title: 'Code Geass' },
  { id: '18', title: 'Steins;Gate' },
  { id: '19', title: 'Re:Zero' },
  { id: '20', title: 'No Game No Life' },
  { id: '21', title: 'The Rising of the Shield Hero' },
  { id: '22', title: 'Mob Psycho 100' },
  { id: '23', title: 'Dr. Stone' },
  { id: '24', title: 'Vinland Saga' },
  { id: '25', title: 'Erased' },
  { id: '26', title: 'Akame ga Kill!' },
  { id: '27', title: 'The Seven Deadly Sins' },
  { id: '28', title: 'Parasyte: The Maxim' },
  { id: '29', title: 'Berserk' },
  { id: '30', title: 'Blue Exorcist' },
  { id: '31', title: 'Noragami' },
  { id: '32', title: 'Psycho-Pass' },
  { id: '33', title: 'Charlotte' },
  { id: '34', title: 'Guilty Crown' },
  { id: '35', title: 'Elfen Lied' },
  { id: '36', title: 'Claymore' },
  { id: '37', title: 'Toradora!' },
  { id: '38', title: 'Clannad' },
  { id: '39', title: 'Angel Beats!' },
  { id: '40', title: 'Anohana' },
  { id: '41', title: 'Your Lie in April' },
  { id: '42', title: 'A Silent Voice' },
  { id: '43', title: 'Your Name' },
  { id: '44', title: 'Weathering With You' },
  { id: '45', title: 'I Want to Eat Your Pancreas' },
  { id: '46', title: 'Kimi ni Todoke' },
  { id: '47', title: 'Fruits Basket' },
  { id: '48', title: 'Horimiya' },
  { id: '49', title: 'Rent-A-Girlfriend' },
  { id: '50', title: 'The Quintessential Quintuplets' },
  { id: '51', title: 'Kaguya-sama: Love is War' },
  { id: '52', title: 'Tonikaku Kawaii' },
  { id: '53', title: 'Nisekoi' },
  { id: '54', title: 'Toriko' },
  { id: '55', title: 'Great Teacher Onizuka' },
  { id: '56', title: 'Hajime no Ippo' },
  { id: '57', title: 'Haikyuu!!' },
  { id: '58', title: 'Kuroko no Basket' },
  { id: '59', title: 'Yowamushi Pedal' },
  { id: '60', title: 'Free!' },
  { id: '61', title: 'SK8 the Infinity' },
  { id: '62', title: 'Initial D' },
  { id: '63', title: 'Baki' },
  { id: '64', title: 'JoJo’s Bizarre Adventure' },
  { id: '65', title: 'Trigun' },
  { id: '66', title: 'Hellsing' },
  { id: '67', title: 'Devilman Crybaby' },
  { id: '68', title: 'Dorohedoro' },
  { id: '69', title: 'Beastars' },
  { id: '70', title: 'Zom 100: Bucket List of the Dead' },
  { id: '71', title: 'Chainsaw Man' },
  { id: '72', title: 'Pluto' },
  { id: '73', title: 'Made in Abyss' },
  { id: '74', title: 'The Promised Neverland' },
  { id: '75', title: '86' },
  { id: '76', title: 'Takt Op. Destiny' },
  { id: '77', title: 'Lycoris Recoil' },
  { id: '78', title: 'Call of the Night' },
  { id: '79', title: 'Bocchi the Rock!' },
  { id: '80', title: 'Ousama Ranking' },
  { id: '81', title: 'Spy x Family' },
  { id: '82', title: 'Hell’s Paradise' },
  { id: '83', title: 'Blue Lock' },
  { id: '84', title: 'Welcome to the NHK' },
  { id: '85', title: 'Golden Kamuy' },
  { id: '86', title: 'Mushoku Tensei' },
  { id: '87', title: 'That Time I Got Reincarnated as a Slime' },
  { id: '88', title: 'Overlord' },
  { id: '89', title: 'Konosuba' },
  { id: '90', title: 'Jobless Reincarnation' },
  { id: '91', title: 'Log Horizon' },
  { id: '92', title: 'DanMachi' },
  { id: '93', title: 'Goblin Slayer' },
  { id: '94', title: 'Grimgar, Ashes and Illusions' },
  { id: '95', title: 'Cautious Hero' },
  { id: '96', title: 'How Not to Summon a Demon Lord' },
  { id: '97', title: 'The World’s Finest Assassin' },
  { id: '98', title: 'Arifureta' },
  { id: '99', title: 'Redo of Healer' },
  { id: '100', title: 'Reincarnated as a Sword' },
];

export default function AnimeListScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Anime List</Text>
      <FlatList
        data={animeData}
        keyExtractor={(item) => item.id}
        renderItem={({ item }) => <Text style={styles.item}>{item.id}. {item.title}</Text>}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 10 },
  item: { fontSize: 18, paddingVertical: 5 },
});
